name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build-pr-preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    concurrency:
      group: pr-preview-build-${{ github.event.number }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build Jekyll site
        # Builds the site natively to the _site/ directory and dynamically sets the baseurl
        run: bundle exec jekyll build --baseurl /${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.number }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: preview-site-${{ github.event.number }}
          path: _site/

  deploy-pr-preview:
    needs: build-pr-preview
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.build-pr-preview.result == 'success' || github.event.action == 'closed') }}
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: "pages-deploy-queue" # Must match github-pages.yml!
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6

      - name: Download Artifact
        if: github.event.action != 'closed'
        uses: actions/download-artifact@v8`
        with:
          name: preview-site-${{ github.event.number }}
          path: _site/

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site/
          wait-for-pages-deployment: true
